- hosts: jumpbox
#  become: yes
  roles:
     - create-network
     - create-keypair
     - create-securitygroup
     - create-flavor
  tasks:
##Create Fronend Instance
  - name: Create frontend instance
    include_role:
       name: create_instance
       vars_from: frontend.yml
###Create App1 server 
  - name: Create app1 instance
    include_role:
       name: create_instance
       vars_from: app1.yml
##Create App2 server
  - name: Create app2 instance
    include_role:
       name: create_instance
       vars_from: app2.yml
##Create DB server
  - name: Create db instance
    include_role:
       name: create_instance
       vars_from: db.yml
## Alternate Method to create dynmaic inventory
#  - name: Gather facts
#    include_role: 
#       name: create-facts
#    tags:
#     - test_inventory
