---
- name: Compress the backup data.
  shell: tar cvfz ../tower-backup-{{ now }}.tar.gz .
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/{{ now }}/'
  notify: Remove the backup tarball.

- name: Download the database dump.
  fetch:
    dest: '{{ backup_dest }}'
    fail_on_missing: yes
    flat: yes
    src: '{{ backup_dir.rstrip("/") }}/tower-backup-{{ now }}.tar.gz'

- name: Create symbolic link to the most recent backup
  local_action: file
  args:
    state: 'link'
    src: '{{ backup_dest.rstrip("/") }}/tower-backup-{{ now }}.tar.gz'
    path: '{{ backup_dest.rstrip("/") }}/tower-backup-latest.tar.gz'
    force: yes
  become: false
