---
# clean drops the database
# create adds instructions to create the database
# Note: user needs access to postgres template when restoring
- name: Perform a PostgreSQL dump.
  shell: "pg_dump --clean --create --host='{{ tower_db_settings.default.HOST }}' --port={{ tower_db_settings.default.PORT }} --username='{{ tower_db_settings.default.USER  }}' --dbname='{{ tower_db_settings.default.NAME }}' > tower.db"
  args:
    chdir: '{{ backup_dir.rstrip("/") }}/{{ now }}/'
  environment:
    PGPASSWORD: "{{ tower_db_settings.default.PASSWORD }}"
  no_log: True
