---
# Indicate whether to verify gpg signatures during install
gpgcheck: 1

aw_user: awx
aw_group: awx
awx_install_home: '/var/lib/awx'

isolated_package_name: ansible-tower-isolated

# Indicate whether to upgrade Ansible as well as Tower
upgrade_ansible_with_tower: false
